Use 0.9.3 as new baseline for bincompat
This is required because 0.9.3 introduced a new module:

sbt.librarymanagement.ResolveException: unresolved dependency:
eu.timepit#refined-scalacheck_1.13_2.12;0.9.0: not found